### ISSUE TITLE
not inserting jsdoc comments

### ISSUE THREAD

**Issue by lallenfrancisl** [fannheyward/coc-docthis#104]
![doc this not working](https://user-images.githubusercontent.com/21018348/119277683-b07e6600-bc3e-11eb-830c-272af568cdec.gif)

As seen in the gif the suggestion comes but its not inserted

neovim version: v0.4.4
OS: ubuntu 20.04

**Comment by fannheyward** [comment]
Put your cursor on `limitCacheSize`, run `:CocCommand docthis.documentThis`, the completion maybe error.
